## Notebook to test the sklearn model

In [57]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier

import matplotlib
import matplotlib.pyplot as plt

%matplotlib inline

In [58]:
df = pd.read_csv('plagiarism_data/train.csv', header=None, names=None)
df.head()

0         1         2         3         4
0  0  0.398148  0.079070  0.000000  0.191781
1  1  0.869369  0.719457  0.319444  0.846491
2  1  0.593583  0.268817  0.044199  0.316062
3  0  0.544503  0.115789  0.000000  0.242574
4  0  0.329502  0.053846  0.000000  0.161172

In [59]:
train_x = df.loc[:,1:]
train_x.head()

1         2         3         4
0  0.398148  0.079070  0.000000  0.191781
1  0.869369  0.719457  0.319444  0.846491
2  0.593583  0.268817  0.044199  0.316062
3  0.544503  0.115789  0.000000  0.242574
4  0.329502  0.053846  0.000000  0.161172

In [60]:
train_y = df.loc[:,0]
train_y.head()

0    0
1    1
2    1
3    0
4    0
Name: 0, dtype: int64

In [61]:
# shuffle the dataset
train_x = train_x.sample(frac=1)

In [62]:
scaler = MinMaxScaler()
train_x = scaler.fit_transform(train_x.to_numpy())
print(train_x[:10,:])

[[3.40346753e-01 3.07444853e-01 2.18748061e-01 1.53480260e-01]
 [4.02615811e-01 2.45967742e-01 4.69272219e-02 1.92493578e-01]
 [1.00000000e+00 9.60336538e-01 8.06913580e-01 8.95823035e-01]
 [3.97802664e-01 1.23893805e-01 0.00000000e+00 1.75480936e-01]
 [1.82102456e-02 3.59195402e-04 0.00000000e+00 0.00000000e+00]
 [2.80213638e-01 6.49287565e-02 0.00000000e+00 8.03808961e-02]
 [3.09156627e-01 1.08668342e-01 0.00000000e+00 1.26851671e-01]
 [6.11240775e-02 1.31578947e-03 0.00000000e+00 1.03188334e-02]
 [9.27494732e-01 8.74577703e-01 7.87733971e-01 8.10509389e-01]
 [7.99196787e-01 6.54361264e-01 1.79953965e-01 7.53370682e-01]]


In [63]:
train_x.shape

(70, 4)

In [64]:
# split into training and validation set for cross validation
train_ratio = 0.8
train_size = int(train_x.shape[0] * train_ratio)

# get the validation data
val_x = train_x[train_size:, :]
val_y = train_y[train_size:]

# get the training data
train_x = train_x[:train_size, :]
train_y = train_y[:train_size]

### Testing AdaBoostClassifier

In [92]:
model = AdaBoostClassifier(n_estimators=500, learning_rate=0.001)
model.fit(final_train_x, final_train_y)
print('accuracy = {};'.format(model.score(val_x, val_y)))

accuracy = 0.5714285714285714;


### Testing RandomForest Classifier

In [83]:
model = RandomForestClassifier(min_samples_leaf=20)
model.fit(final_train_x, final_train_y)
print('accuracy = {};'.format(model.score(val_x, val_y)))

accuracy = 0.7142857142857143;
